//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenBasedAuthDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Request_Status
    {
        public int Sr_status_id { get; set; }
        public string Sr_Status_Code { get; set; }
        public string Sr_status_Desc { get; set; }
    }
}
