//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenBasedAuthDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_login
    {
        public int Login_id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Role_id { get; set; }
        public string User_password { get; set; }
        public string Role_Code { get; set; }
        public string Last_login_date { get; set; }
        public string last_pasword_reset_on { get; set; }
        public string Valid_Login { get; set; }
        public string Valid_password { get; set; }
    
        public virtual App_Users App_Users { get; set; }
        public virtual User_Roles User_Roles { get; set; }
    }
}
