//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CableManagmentApis
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public App_Users()
        {
            this.User_login = new HashSet<User_login>();
        }
    
        public int User_id { get; set; }
        public string User_Name { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string Email_Add { get; set; }
        public string User_Address { get; set; }
        public string User_Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_login> User_login { get; set; }
    }
}
